version: 2
models:
    - name: project_timings
      description: "Includes project names ids and duration worked."
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: name
            description: "Project Name"
            tests:
                - unique
                - not_null
          - name: minutes
            description: "Duration in minutes"
            tests:
                - unique
                - not_null
            
        